<script lang="ts">
	import PhotographyImage from '$lib/PhotographyImage.svelte';
	import AnimateIn from '$lib/AnimateIn.svelte';
	import { procreateArt } from '$lib/sitedata';
</script>

<h1 class="angletext">Procreate</h1>
<p>
	Most of my art is generated by code but occasionally I like to doodle on my iPad. I'm still
	figuring out different techniques for creating digital art by hand and Procreate has many tools,
	filters and brushes to explore.
</p>

<div class="photogrid">
	{#each procreateArt as { filename, alt }}
		<div class="imgcontainer">
			<AnimateIn
				from="transform: translateX(5px) translateY(50px) rotateY(20deg); opacity: 0;"
				to="transform: translateX(0) translateY(0) rotateY(0deg); opacity: 1;"
			>
				<PhotographyImage src="/procreate/{filename}" {alt} />
			</AnimateIn>
		</div>
	{/each}
</div>

<style lang="scss">
	.photogrid {
		display: grid;
		gap: clamp(2vw, 8vw, 5rem);
		padding: clamp(4vw, 8vw, 5rem) 0;
		background: var(--card-backgroundcolor);
		box-shadow:
			-50vw 0 0 var(--card-backgroundcolor),
			50vw 0 0 var(--card-backgroundcolor);
		perspective: 1000px;
	}

	.imgcontainer {
		margin: 0 auto;
		position: relative;
		border-radius: clamp(0.5vw, 1vw, 1rem);

		@media screen and (min-width: 600px) {
			width: 80%;
			&:nth-child(odd) {
				left: -10%;
			}
			&:nth-child(even) {
				right: -10%;
			}
		}
	}
</style>
